sda:
  pgvector:
    # An integer that specifies the maximum number of similar documents to return.
    k_nearest_neighbors: 5
    # Only documents with a similarity above this value are returned.
    similarity_threshold: 0.75

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      url: /api-docs.yaml

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4-turbo-preview

  docker:
    compose:
      lifecycle-management: start-and-stop

  datasource:
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: mypassword