sda:
  pgvector:
    # An integer that specifies the maximum number of similar documents to return.
    k_nearest_neighbors: 5
    # Only documents with a similarity above this value are returned.
    similarity_threshold: 0.75

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      url: /api-docs.yaml

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          # The model to use for the chat. possible values are: gpt-3-turbo, gpt-4-turbo, gpt-4-turbo-preview
          model: gpt-4-turbo-preview
          # The temperature of the model. Must be a float between 0 and 1. Higher values mean the model will take more risks.
          temperature: 0.1

  docker:
    compose:
      lifecycle-management: start-and-stop

  datasource:
    url: jdbc:postgresql://localhost/mydatabase
    username: myuser
    password: mypassword
